### ISSUE TITLE
我利用RotatedCOCOEvaluator函数评估只得到了25.7的精度

### ISSUE THREAD

**Issue by dxx111** [marcelsheeny/radiate_sdk#10]
我利用RotatedCOCOEvaluator函数评估只得到了25.7的精度，不知道自己的代码哪里出错了，求作者分享一下评估模型的代码，谢谢您。

**Comment by dxx111** [comment]
I used the RotatedCOCOEvaluator function to evaluate and only got an accuracy of 25.7. I don’t know where my code went wrong. I ask the author to share the code of the evaluation model. Thank you.

**Comment by rlaehddls9** [comment]
> I used the RotatedCOCOEvaluator function to evaluate and only got an accuracy of 25.7. I don’t know where my code went wrong. I ask the author to share the code of the evaluation model. Thank you.

Are you solve this prob?
