### ISSUE TITLE
Train-Test data for the pre-trained model provided

### ISSUE THREAD

**Issue by Madhusakth** [marcelsheeny/radiate_sdk#22]
I wanted to run an evaluation on the pre-trained models provided and you said that you used data from both good and bad weather. Could you please specify the data folders/timestamps you used for training and testing exactly?

**Comment by Madhusakth** [comment]
After downloading the dataset, I saw that the meta.json indicates if the folder was train/test and so on. 
I think this issue is resolved.

**Comment by nlm676** [comment]
May I ask where is the link to download the dataset? Thank you very much. I made an error during the training, good_weather_test is empty, so I want to download the dataset.
