### ISSUE TITLE
How to evaluate faster_rrcnn_R_50_FPN ?

### ISSUE THREAD

**Issue by rlaehddls9** [marcelsheeny/radiate_sdk#26]
Thanks for good project using Radiate dataset. 
But..
How to evaluate faster_rrcnn_R_50_FPN ? 

First, it causes this assertion.
assert torch.all(match_quality_matrix >= 0)

Therefore I removed above assertion, then I tried to evaluate above model by using RotatedCOCOEvaluator but AP was approximately 25. 

How can I fix it? 

Could you share your rotated faster rcnn implementation code?

**Comment by yangsc4063** [comment]
hi, is there any update for this issue? i met the same problem, thanks for your help.
