### ISSUE TITLE
Questions about 3D Radar information

### ISSUE THREAD

**Issue by MMMHT** [marcelsheeny/radiate_sdk#3]
Hi, My question is that does 3D Radar information available in RADIATE? released Radar (both polar and Cartesian) only containing 2D information (position x, y). While Navetch Radar capable obtain altitude information( 1.8° elevation resolution) according to the [description](http://pro.hw.ac.uk/radiate/doc/dataset/). Is there any way I could obtain a point cloud using RADIATE?

Any help will be appreciated!

**Comment by marcelsheeny** [comment]
Hi, the Navtech Radar that we used does not provide 3D point cloud. This radar just have 1 transmitter and 1 receiver, that is different from a Velodyne lidar which has multiple channels (up to 64), enabling 3D measurements. The elevation angle resolution from radar gives the information how detectable is an object depending on the distance and height from the sensor.
 
The information in the navtech website can probably give you a better understanding.
https://navtechradar.atlassian.net/wiki/spaces/PROD/pages/28770363/Optimizing+the+sensor+position

**Comment by MMMHT** [comment]
thanks for your prompt reply! I do make the wrong understanding regarding the elevation angle.
