### ISSUE TITLE
How to evaluate the accuracy of a model with a rotation angle on the radiate dataset?

### ISSUE THREAD

**Issue by dxx111** [marcelsheeny/radiate_sdk#9]
How to evaluate the accuracy of a model with a rotation angle on the radiate dataset?

**Comment by marcelsheeny** [comment]
Hi,

You should use the DOTA PASCAL Average Precision metric. You can find the repository that evaluates here https://github.com/CAPTAIN-WHU/DOTA_devkit . You need to extract the predicted bounding box values and the ground truth in the format described in the DOTA repository.

**Comment by dxx111** [comment]
Okay, thank you very much.

2021-01-23 08:55:25"Marcel Sheeny" <notifications@github.com>写道：

Hi,

You should use the DOTA PASCAL Average Precision metric. You can find the repository that evaluates here https://github.com/CAPTAIN-WHU/DOTA_devkit . You need to extract the predicted bounding box values and the ground truth in the format described in the DOTA repository.

**Comment by dxx111** [comment]
Can you share the code of the evaluation model with me?

2021-01-23 08:55:25"Marcel Sheeny" <notifications@github.com>写道：

Hi,

You should use the DOTA PASCAL Average Precision metric. You can find the repository that evaluates here https://github.com/CAPTAIN-WHU/DOTA_devkit . You need to extract the predicted bounding box values and the ground truth in the format described in the DOTA repository.

**Comment by dxx111** [comment]
Hello, I tried to use the DOTA toolkit to test the model, the result was lower, I don’t know the reason, can you share your code?

2021-01-23 08:55:25"Marcel Sheeny" <notifications@github.com>写道：

Hi,

You should use the DOTA PASCAL Average Precision metric. You can find the repository that evaluates here https://github.com/CAPTAIN-WHU/DOTA_devkit . You need to extract the predicted bounding box values and the ground truth in the format described in the DOTA repository.

**Comment by dxx111** [comment]
I tried to use the DOTA evaluation code evaluation model, the result is still 28.089, I hope you have time to make your evaluation code public, let me learn your code, thank you.

2021-01-23 08:55:25"Marcel Sheeny" <notifications@github.com>写道：

Hi,

You should use the DOTA PASCAL Average Precision metric. You can find the repository that evaluates here https://github.com/CAPTAIN-WHU/DOTA_devkit . You need to extract the predicted bounding box values and the ground truth in the format described in the DOTA repository.

**Comment by marcelsheeny** [comment]
Can you make sure that you used 0.5 as IoU (Intersection over Union)?

**Comment by dxx111** [comment]
Yes, I really use 0.5 as IOU.

2021-02-01 08:03:07"Marcel Sheeny" <notifications@github.com>写道：

Can you make sure that you used 0.5 as IoU (Intersection over Union)?
